<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'DB' => $baseDir . '/Tazzy/database/db.php',
    'Hash' => $baseDir . '/Tazzy/helpers/hash.php',
    'Mailer' => $baseDir . '/Tazzy/helpers/mail.php',
    'Message' => $baseDir . '/Tazzy/helpers/message.php',
    'QueryBuilder' => $baseDir . '/Tazzy/database/QueryBuilder.php',
    'Session' => $baseDir . '/Tazzy/helpers/session.php',
    'Table' => $baseDir . '/Tazzy/database/table.php',
    'Token' => $baseDir . '/Tazzy/helpers/token.php',
    'Validate' => $baseDir . '/Tazzy/helpers/validate.php',
);
